package com.example.hello;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Simple REST Controller for Hello World endpoints
 * 
 * @RestController annotation combines @Controller and @ResponseBody
 * This means all methods return data directly to the HTTP response body
 */
@RestController
public class HelloController {

    /**
     * Home endpoint - accessible at http://localhost:8080/
     * 
     * @return Welcome message as plain text
     */
    @GetMapping("/")
    public String home() {
        return "🌍 Welcome to Spring Boot Hello World Application!\n\n" +
               "Available endpoints:\n" +
               "• GET / - This home page\n" +
               "• GET /hello - Simple hello message\n" +
               "• GET /hello/{name} - Personalized greeting\n\n" +
               "Application started at: " + getCurrentTime() + "\n" +
               "Java Version: " + System.getProperty("java.version") + "\n" +
               "Spring Boot is running on port 8080! 🚀";
    }

    /**
     * Simple hello endpoint - accessible at http://localhost:8080/hello
     * 
     * @return Hello message as plain text
     */
    @GetMapping("/hello")
    public String hello() {
        return "👋 Hello from Spring Boot!\n\n" +
               "This is a simple REST endpoint that returns plain text.\n" +
               "Time: " + getCurrentTime() + "\n" +
               "This response was generated by Spring Boot running on localhost:8080";
    }

    /**
     * Personalized hello endpoint - accessible at http://localhost:8080/hello/{name}
     * 
     * @param name the name from the URL path
     * @return Personalized greeting message
     */
    @GetMapping("/hello/{name}")
    public String helloName(@PathVariable String name) {
        return "🎉 Hello, " + name + "!\n\n" +
               "Welcome to Spring Boot! This is a personalized greeting.\n" +
               "Your name was captured from the URL path variable.\n" +
               "Time: " + getCurrentTime() + "\n" +
               "Thanks for trying our Spring Boot Hello World application! 😊";
    }

    /**
     * Helper method to get current formatted time
     * 
     * @return formatted current date and time
     */
    private String getCurrentTime() {
        return LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
    }
}
