apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  labels:
    app: nginx
type: Opaque
data:
  # Base64 encoded values (echo -n 'admin' | base64)
  username: YWRtaW4=  # admin
  password: cGFzc3dvcmQxMjM=  # password123
  api-key: bXktc2VjcmV0LWFwaS1rZXk=  # my-secret-api-key
---
# TLS Secret for HTTPS
apiVersion: v1
kind: Secret
metadata:
  name: nginx-tls
  labels:
    app: nginx
type: kubernetes.io/tls
data:
  # Replace with actual base64 encoded certificate and key
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # base64 encoded certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t  # base64 encoded private key
---
# Docker registry secret
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  labels:
    app: nginx
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ1c2VyIiwicGFzc3dvcmQiOiJwYXNzIiwiYXV0aCI6ImRYTmxjanB3WVhOeiJ9fX0=
