# .yamllint.yml - Custom linting configuration for workshop
extends: default

rules:
  # Line length - allow longer lines for URLs and long strings
  line-length:
    max: 120
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Indentation - enforce 2 spaces consistently
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Comments - require space after #
  comments:
    min-spaces-from-content: 1
    require-starting-space: true

  # Empty lines - control blank line usage
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Brackets - consistent spacing in lists
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Braces - consistent spacing in dictionaries
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Boolean values - allow common variations
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false

  # Document markers - make optional for flexibility
  document-start: disable
  document-end: disable

  # Trailing spaces - strict enforcement
  trailing-spaces: enable

  # New line at end of file
  new-line-at-end-of-file: enable
