# fixed-ansible.yml - Clean Ansible playbook
---
- name: Deploy Web Application
  hosts: webservers
  become: true
  vars:
    app_name: myapp
    app_version: 1.0.0
    app_port: 8080

  tasks:
    - name: Update package cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name: ['nginx', 'python3', 'python3-pip']
        state: present

    - name: Create application directory
      file:
        path: /opt/{{ app_name }}
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy application files
      copy:
        src: ./app/
        dest: /opt/{{ app_name }}/
        owner: www-data
        group: www-data
        mode: '0644'
      notify: restart nginx

    - name: Template nginx configuration
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/{{ app_name }}
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
